import time

def cleany(finger):
    print (finger * 8)


cleany('      .       ')
time.sleep(.2)
cleany('      .       ')
time.sleep(.2)
cleany('      .       ')
time.sleep(.2)
cleany('      +       ')
time.sleep(.2)
cleany('      +       ')
time.sleep(.2)
cleany('      +       ')
time.sleep(.2)
cleany('      *       ')
time.sleep(.2)
cleany('      *       ')
time.sleep(.2)
cleany('      *       ')
time.sleep(.2)
cleany('      8       ')
time.sleep(.2)
cleany('      8       ')
time.sleep(.2)
cleany('      8       ')
time.sleep(.2)
cleany('     888      ')
time.sleep(.2)
cleany('     888      ')
time.sleep(.2)
cleany('     888      ')
time.sleep(.2)
cleany('    88888     ')
time.sleep(.2)
cleany('   88 8 88    ')
time.sleep(.2)
cleany('  8   8   8   ')
time.sleep(.2)
cleany(' 8    8    8  ')
time.sleep(.2)
cleany(' 8    8    8  ')
time.sleep(.2)
cleany(' 8    8    8  ')
time.sleep(.2)
cleany(' 8    8    8  ')
time.sleep(.2)
cleany(' 8    8    8  ')
time.sleep(.2)
cleany(' 8  8 8 8  8  ')
time.sleep(.2)
cleany(' 8  8 8 8  8  ')
time.sleep(.2)
cleany(' 8 88 8 88 8  ')
time.sleep(.2)
cleany(' 8 88 8 88 8  ')
time.sleep(.2)
cleany(' 8 88 8 88 8  ')
time.sleep(.2)
cleany('8 888 8 888 8 ')
time.sleep(.2)
cleany('')


